services:

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - /tmp/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    networks:
      - kotlin-app

  app:
    build:
      context: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - APP_SERVER=postgres
    networks:
      - kotlin-app

networks:
  kotlin-app:
